#!/bin/bash

a=$(pwd|awk -F "/" '{print $NF}')
if [ -z $1 ]
        then
                echo which is down?
                VBoxManage list vms|awk '/'$a'/ {print $0}'|nl
                echo -n "print number(1 or 2 or ...):"
                read u
                id=$(VBoxManage list vms|awk '/'$a'/ {print $0}'|nl|grep "     $u"|awk '{print $3}')
        else
                id=$(VBoxManage list vms|grep $a|awk '/'$1'/ {print $2}')
fi
VBoxManage controlvm $id poweroff
