#!/bin/bash
RES=~/.local/tmp_1

a=$(pwd|awk -F "/" '{print $NF}')
if [ -z $1 ]
        echo "Waiting vagrant status..."
        then
#       if [ 1 == $(VBoxManage list vms|grep $a|wc -l) ]
        vagrant status|awk '/virtualbox/ {print $1}'>$RES
#       if [ 1 == $(vagrant status|awk '/virtualbox/ {print $1}'|wc -l) ]
        if [ 1 == $(cat $RES|wc -l) ]
               then
#               id=$(VBoxManage list vms|awk '/'$a'/ {print $2}')
#               id=$(vagrant status|awk '/virtualbox/ {print $1}')
                id=$(cat $RES)
                else
                        echo -e "\e[31mwhich is up?\e[0m"
#                       VBoxManage list vms|awk '/'$a'/ {print $0}'|nl
#                       vagrant status|awk '/virtualbox/ {print $1}'|nl
                        cat $RES|nl
                        echo -n "print number(1 or 2 or ...):"
                        read u
#                     id=$(vagrant status|awk '/virtualbox/ {print $0}'|nl|grep "     $u"|awk '{print $2}')
                      id=$(cat $RES|nl|grep "     $u"|awk '{print $2}')
        fi
        else
#               id=$(VBoxManage list vms|grep $a|awk '/'$1'/ {print $2}')
                id=$(VBoxManage list vms|awk '/'$1'/ {print $2}')
fi
VBoxManage startvm $id --type headless

