#!/bin/bash
a=$(pwd|awk -F "/" '{print $NF}')
if [ -z $1 ]
        then
        if [ 1 == $(VBoxManage list vms|grep $a|wc -l) ]
                then
                id=$(VBoxManage list vms|awk '/'$a'/ {print $2}')
                else
                        echo -e "\e[31which is up?\e[0m"
                        VBoxManage list vms|awk '/'$a'/ {print $0}'|nl
                        echo -n "print number(1 or 2 or ...):"
                        read u
                        id=$(VBoxManage list vms|awk '/'$a'/ {print $0}'|nl|grep "     $u"|awk '{print $3}')
        fi
        else
                id=$(VBoxManage list vms|grep $a|awk '/'$1'/ {print $2}')
fi
VBoxManage startvm $id --type headless
